packages:
  - 'morse-audio/packages/*'
  - 'morse-audio/apps/*'
  - 'cw-decode/apps'

onlyBuiltDependencies:
  - esbuild
  - onnxruntime-node
  - protobufjs
allowBuilds:
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
