"""
CWNet-focused DSP scoring harness. The agent must not edit this file.

Loads evaldata/ NPZs (generated by generate_eval.py), runs dsp.extract_envelope(),
and scores using CWNet-relevant metrics: timing accuracy, AUC, F1, IoU, rise_ms.

All scoring is done at 500 Hz (ENVELOPE_SR) — the native DSP output rate.

Usage: python evaluate.py
Prints composite score and diagnostics to stdout.
"""
import sys
import time
from pathlib import Path

import numpy as np
from scipy.optimize import minimize
from scipy.special import expit

from constants import (
    AUDIO_SR, EVAL_DIR, MAX_CHANNELS, MIN_CHANNELS, N_EVAL_SAMPLES,
    SNR_TIERS, WPM_TIERS, W_AUC, W_F1, W_IOU, W_RISE, W_TIMING,
)

SR = 500  # scoring sample rate (ENVELOPE_SR)

# Aux-channel info-gain bonus: probe_AUC(all channels) - AUC(ch0) per sample.
# Only rewards aux channels for adding linearly-extractable tone-presence info
# beyond ch0. A pure metadata channel (e.g. noise level uncorrelated with ON/OFF)
# earns ~0; a complementary presence detector (e.g. phase coherence) earns more.
W_INFOGAIN = 0.15

# Tier weights for the headline `composite:` score. Steers the autoresearch loop
# toward the operationally-hard regions (low SNR + fast dits) instead of averaging
# them away with easier samples. The reported `composite:` is the mean of an
# SNR-weighted composite and a WPM-weighted composite so both axes are steered.
# Weights auto-renormalize over tiers that have ≥1 sample in the eval set.
SNR_TIER_WEIGHTS = {"very_low": 0.35, "low": 0.30, "mid": 0.20, "high": 0.15}
WPM_TIER_WEIGHTS = {"slow":     0.15, "mid": 0.30, "fast": 0.35, "vfast": 0.20}


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_samples():
    eval_dir = Path(EVAL_DIR)
    if not eval_dir.exists():
        print(f"ERROR: {EVAL_DIR}/ not found — run: uv run python generate_eval.py")
        sys.exit(1)

    npzs = sorted(eval_dir.glob("sample_*.npz"))
    if not npzs:
        print(f"ERROR: no samples in {EVAL_DIR}/ — run: uv run python generate_eval.py")
        sys.exit(1)

    samples = []
    for path in npzs[:N_EVAL_SAMPLES]:
        d = np.load(path, allow_pickle=True)
        samples.append({
            "audio":    d["audio"].astype(np.float32),
            "gt_500":   d["gt_binary"].astype(np.float32),  # (T_500,) at 500 Hz
            "snr_db":   float(d["snr_db"]),
            "wpm":      float(d["wpm"]),
            "tone_freq": float(d["tone_freq"]),
        })
    return samples


# ---------------------------------------------------------------------------
# Metrics — all at 500 Hz
# ---------------------------------------------------------------------------

def _auc(soft, gt):
    """ROC AUC via Mann–Whitney U (rank-based). O(n log n) with tie correction.

    Equivalent to the trapezoidal ROC integral to within float precision, but
    stable on long arrays (the scorer calls this on the full stacked eval set
    for marginal-info-gain probes, where O(n²) per-threshold sweeps were taking
    several minutes).
    """
    from scipy.stats import rankdata  # local import keeps cold-start lean
    gt_bool = gt.astype(bool)
    n_pos = int(np.sum(gt_bool))
    n_neg = int(np.sum(~gt_bool))
    if n_pos == 0 or n_neg == 0:
        return 0.5
    ranks = rankdata(soft)
    sum_pos = float(ranks[gt_bool].sum())
    return (sum_pos - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)


def _norm_rms_timing(soft, gt, wpm, sr=SR):
    """RMS edge timing error / dit_duration. Lower = sharper edges."""
    gt_edges = np.where(np.diff(gt.astype(int)) != 0)[0]
    pred_edges = np.where(np.diff((soft > 0.5).astype(int)) != 0)[0]

    if len(gt_edges) == 0 or len(pred_edges) == 0:
        return 2.0

    errors_ms = [
        abs(int(pred_edges[np.argmin(np.abs(pred_edges - ge))]) - int(ge)) / sr * 1000.0
        for ge in gt_edges
    ]
    rms_ms = float(np.sqrt(np.mean(np.array(errors_ms) ** 2)))
    dit_ms = 1200.0 / wpm
    return rms_ms / dit_ms


def _f1(soft, gt):
    pred = (soft > 0.5).astype(np.float32)
    gt = gt.astype(np.float32)
    tp = float(np.sum(pred * gt))
    fp = float(np.sum(pred * (1.0 - gt)))
    fn = float(np.sum((1.0 - pred) * gt))
    return tp / max(tp + 0.5 * (fp + fn), 1e-9)


def _iou(soft, gt):
    pred = soft > 0.5
    gt_bool = gt.astype(bool)
    return float(np.sum(pred & gt_bool)) / max(float(np.sum(pred | gt_bool)), 1.0)


def _rise_ms(soft, gt, sr=SR):
    """Mean 10→90% rise time at tone onsets (ms). Lower = sharper = better."""
    onsets = np.where(np.diff(gt.astype(int)) > 0)[0]
    times = []
    window = int(0.15 * sr)  # 150 ms
    for e in onsets:
        seg = soft[e: e + window]
        if len(seg) < 5:
            continue
        above_10 = np.where(seg >= 0.1)[0]
        above_90 = np.where(seg >= 0.9)[0]
        if len(above_10) and len(above_90):
            times.append((above_90[0] - above_10[0]) / sr * 1000.0)
    return float(np.mean(times)) if times else 999.0


def _fall_ms(soft, gt, sr=SR):
    """Mean 90→10% fall time at tone offsets (ms). Lower = sharper = better.
    Symmetric to _rise_ms; CTC also relies on clean offset alignment."""
    offsets = np.where(np.diff(gt.astype(int)) < 0)[0]
    times = []
    window = int(0.15 * sr)
    for e in offsets:
        seg = soft[e: e + window]
        if len(seg) < 5:
            continue
        below_90 = np.where(seg <= 0.9)[0]
        below_10 = np.where(seg <= 0.1)[0]
        if len(below_90) and len(below_10):
            times.append((below_10[0] - below_90[0]) / sr * 1000.0)
    return float(np.mean(times)) if times else 999.0


def _weighted_mean_by_tier(scores_by_tier, weights):
    """Weighted mean over tiers, renormalized across tiers that have samples."""
    present = {t: scores_by_tier[t] for t in weights if scores_by_tier.get(t)}
    if not present:
        return 0.0
    total_w = sum(weights[t] for t in present)
    return float(sum(weights[t] * np.mean(present[t]) for t in present) / total_w)


def _envelope_score(norm_timing, auc, f1, iou, rise_ms_val, wpm):
    """Composite on ch0 alone — the tone-presence envelope for CTC."""
    dit_ms = 1200.0 / wpm
    timing_score = max(0.0, 1.0 - norm_timing)
    rise_score = max(0.0, 1.0 - rise_ms_val / (0.5 * dit_ms))
    return (
        W_TIMING * timing_score
        + W_AUC * auc
        + W_F1 * f1
        + W_IOU * iou
        + W_RISE * rise_score
    )


def _fit_logreg(X, y, max_iter=200):
    """Logistic regression with bias, numpy/scipy only.

    X: (N, C) frame-stacked channels. y: (N,) binary. Returns (w (C,), b).
    For C=1 the resulting sigmoid is monotonic in X, so probe AUC == ch0 AUC
    (info_gain == 0), which is the desired sanity property.
    """
    n, C = X.shape
    y = y.astype(np.float64)

    def loss_and_grad(params):
        w, b = params[:C], params[C]
        logits = X @ w + b
        # Numerically stable BCE: mean(logaddexp(0, logits) - y*logits)
        loss = float(np.mean(np.logaddexp(0.0, logits) - y * logits))
        p = expit(logits)
        dw = X.T @ (p - y) / n
        db = float(np.mean(p - y))
        return loss, np.concatenate([dw, [db]])

    x0 = np.zeros(C + 1)
    res = minimize(loss_and_grad, x0, jac=True, method="L-BFGS-B",
                   options={"maxiter": max_iter})
    return res.x[:C], float(res.x[C])


def _snr_tier(snr_db):
    for name, (lo, hi) in SNR_TIERS.items():
        if lo <= snr_db < hi:
            return name
    return "high"


def _wpm_tier(wpm):
    for name, (lo, hi) in WPM_TIERS.items():
        if lo <= wpm < hi:
            return name
    return "vfast"


# ---------------------------------------------------------------------------
# Main evaluation
# ---------------------------------------------------------------------------

def run_evaluation():
    t0 = time.time()

    try:
        import dsp
    except Exception as e:
        print(f"IMPORT_ERROR: {e}")
        sys.exit(1)

    samples = load_samples()
    if not samples:
        print("ERROR: no samples loaded")
        sys.exit(1)

    # ------------------------------------------------------------------
    # Pass 1: extract envelopes, align with gt, validate shapes.
    # ------------------------------------------------------------------
    extracted = []  # list of (env (T,C), gt (T,), sample_dict)
    n_channels = None

    for i, s in enumerate(samples):
        try:
            env = dsp.extract_envelope(
                s["audio"], sample_rate=AUDIO_SR, tone_freq=s["tone_freq"]
            )
        except Exception as e:
            print(f"DSP_ERROR on sample {i}: {e}")
            sys.exit(1)

        if env.ndim == 1:
            env = env[:, np.newaxis]

        if n_channels is None:
            n_channels = env.shape[1]
            if not (MIN_CHANNELS <= n_channels <= MAX_CHANNELS):
                print(f"CHANNEL_ERROR: {n_channels} channels, must be {MIN_CHANNELS}–{MAX_CHANNELS}")
                sys.exit(1)
        elif env.shape[1] != n_channels:
            print(f"CHANNEL_ERROR: inconsistent channels {env.shape[1]} vs {n_channels}")
            sys.exit(1)

        gt = s["gt_500"]
        min_T = min(env.shape[0], len(gt))
        env = env[:min_T].astype(np.float64)
        gt = gt[:min_T].astype(np.float64)
        extracted.append((env, gt, s))

    # ------------------------------------------------------------------
    # Fit logistic probe globally on stacked (env, gt).
    # For C=1 the probe is AUC-identical to ch0 (monotonic sigmoid), so the
    # info_gain bonus is ~0 and composite reduces to envelope_score(ch0).
    # ------------------------------------------------------------------
    if n_channels > 1:
        X_stack = np.concatenate([e for e, _, _ in extracted], axis=0)
        y_stack = np.concatenate([g for _, g, _ in extracted], axis=0)
        w_probe, b_probe = _fit_logreg(X_stack, y_stack)

        # Marginal info-gain per aux channel: AUC(ch0, chk) - AUC(ch0) via a 2-col
        # probe. Exposes dead aux channels that the global probe could otherwise
        # hide behind a strong neighbor.
        auc_ch0_global = _auc(X_stack[:, 0], y_stack)
        marginal_info_gain = {}
        for k in range(1, n_channels):
            X_pair = X_stack[:, [0, k]]
            wk, bk = _fit_logreg(X_pair, y_stack)
            probe_k = expit(X_pair @ wk + bk)
            marginal_info_gain[k] = max(0.0, _auc(probe_k, y_stack) - auc_ch0_global)
    else:
        w_probe, b_probe = None, None
        marginal_info_gain = {}

    # ------------------------------------------------------------------
    # Pass 2: score each sample on ch0 metrics + info-gain bonus.
    # ------------------------------------------------------------------
    results_by_snr = {tier: [] for tier in SNR_TIERS}
    results_by_wpm = {tier: [] for tier in WPM_TIERS}
    all_composites = []
    all_envelope = []
    all_norm_timing = []
    all_auc = []
    all_f1 = []
    all_iou = []
    all_rise = []
    all_info_gain = []
    per_channel_auc = [[] for _ in range(n_channels)]
    per_channel_rise = [[] for _ in range(n_channels)]
    per_channel_fall = [[] for _ in range(n_channels)]
    per_channel_norm_timing = [[] for _ in range(n_channels)]
    issues = []

    for i, (env, gt, s) in enumerate(extracted):
        ch0 = env[:, 0]

        # Per-channel AUC + temporal diagnostics (rise/fall/norm_timing).
        # Slow aux channels (long windows) can still earn info_gain, but their
        # temporal cost must stay visible so the loop doesn't regress edge sharpness.
        for c in range(n_channels):
            ch = env[:, c]
            try:
                per_channel_auc[c].append(_auc(ch, gt))
            except Exception:
                per_channel_auc[c].append(0.5)
            per_channel_rise[c].append(_rise_ms(ch, gt))
            per_channel_fall[c].append(_fall_ms(ch, gt))
            per_channel_norm_timing[c].append(_norm_rms_timing(ch, gt, s["wpm"]))

        wpm = s["wpm"]
        norm_timing = _norm_rms_timing(ch0, gt, wpm)
        auc = _auc(ch0, gt)
        f1 = _f1(ch0, gt)
        iou = _iou(ch0, gt)
        rise_ms_val = _rise_ms(ch0, gt)
        env_score = _envelope_score(norm_timing, auc, f1, iou, rise_ms_val, wpm)

        if w_probe is not None:
            probe = expit(env @ w_probe + b_probe)
            probe_auc = _auc(probe, gt)
            info_gain = max(0.0, probe_auc - auc)  # clip negative (probe overfit noise)
        else:
            info_gain = 0.0

        comp = env_score + W_INFOGAIN * info_gain

        snr_tier = _snr_tier(s["snr_db"])
        if snr_tier in results_by_snr:
            results_by_snr[snr_tier].append(comp)

        wpm_tier = _wpm_tier(wpm)
        if wpm_tier in results_by_wpm:
            results_by_wpm[wpm_tier].append(comp)

        all_composites.append(comp)
        all_envelope.append(env_score)
        all_norm_timing.append(norm_timing)
        all_auc.append(auc)
        all_f1.append(f1)
        all_iou.append(iou)
        all_rise.append(rise_ms_val)
        all_info_gain.append(info_gain)

        if norm_timing > 1.5:
            issues.append(f"sample {i} (snr={s['snr_db']:+.0f}dB wpm={wpm:.0f}): "
                          f"norm_timing={norm_timing:.2f} (very poor)")
        if rise_ms_val > 50.0:
            issues.append(f"sample {i} (snr={s['snr_db']:+.0f}dB wpm={wpm:.0f}): "
                          f"rise_ms={rise_ms_val:.0f} (very slow)")

    elapsed = time.time() - t0

    # Tier-weighted headline composite — steers the loop toward low-SNR + fast WPM.
    # Mean of SNR-weighted and WPM-weighted tier means so both axes pull equally.
    comp_snr_w = _weighted_mean_by_tier(results_by_snr, SNR_TIER_WEIGHTS)
    comp_wpm_w = _weighted_mean_by_tier(results_by_wpm, WPM_TIER_WEIGHTS)
    composite_weighted = 0.5 * (comp_snr_w + comp_wpm_w)
    composite_flat = float(np.mean(all_composites))

    # === STDOUT OUTPUT (parsed by agent) ===
    print(f"composite: {composite_weighted:.4f}")
    print(f"flat_composite: {composite_flat:.4f}  (unweighted mean, legacy)")
    print(f"snr_weighted: {comp_snr_w:.4f}")
    print(f"wpm_weighted: {comp_wpm_w:.4f}")
    print(f"n_channels: {n_channels}")
    print(f"n_samples: {len(samples)}")
    print(f"eval_time_s: {elapsed:.1f}")
    print()

    print("--- per_snr ---")
    for tier in SNR_TIERS:
        scores = results_by_snr[tier]
        if scores:
            print(f"  {tier}: {np.mean(scores):.4f}  (n={len(scores)})")
        else:
            print(f"  {tier}: n/a")
    print()

    print("--- per_wpm ---")
    for tier in WPM_TIERS:
        scores = results_by_wpm[tier]
        lo, hi = WPM_TIERS[tier]
        label = f"{tier}({lo}-{hi}wpm)"
        if scores:
            print(f"  {label}: {np.mean(scores):.4f}  (n={len(scores)})")
        else:
            print(f"  {label}: n/a")
    print()

    print("--- per_channel ---")
    print("  channel   auc   rise_ms  fall_ms  norm_timing")
    for c in range(n_channels):
        a = float(np.mean(per_channel_auc[c])) if per_channel_auc[c] else 0.0
        r = float(np.mean(per_channel_rise[c])) if per_channel_rise[c] else 999.0
        f = float(np.mean(per_channel_fall[c])) if per_channel_fall[c] else 999.0
        nt = float(np.mean(per_channel_norm_timing[c])) if per_channel_norm_timing[c] else 2.0
        print(f"  ch{c}       {a:.4f}  {r:6.1f}  {f:6.1f}  {nt:.3f}")
    print()

    print("--- per_metric ---")
    print(f"  envelope_score: {np.mean(all_envelope):.4f}  (ch0 only)")
    print(f"  info_gain: {np.mean(all_info_gain):.4f}  (probe_auc - ch0_auc, clipped ≥0)")
    if w_probe is not None:
        wstr = ", ".join(f"{wc:+.2f}" for wc in w_probe)
        print(f"  probe: w=[{wstr}]  b={b_probe:+.2f}")
    if marginal_info_gain:
        mstr = ", ".join(f"ch{k}:{v:+.4f}" for k, v in marginal_info_gain.items())
        print(f"  marginal_info_gain: {mstr}  (AUC(ch0,chk) - AUC(ch0))")
    print(f"  norm_timing: {np.mean(all_norm_timing):.3f}")
    print(f"  auc: {np.mean(all_auc):.3f}")
    print(f"  f1: {np.mean(all_f1):.3f}")
    print(f"  iou: {np.mean(all_iou):.3f}")
    print(f"  rise_ms: {np.mean(all_rise):.1f}")
    print()

    if issues:
        print("--- issues ---")
        for iss in issues[:10]:
            print(f"  {iss}")
    else:
        print("--- issues: none ---")


if __name__ == "__main__":
    run_evaluation()
