// ITU International Call Sign Series → country + flag, from ITU Appendix 42 /
// ARRL. Each entry covers a contiguous prefix range "START-END" (compared on
// the leading characters of a callsign); see `callsignCountry` in callsign.ts
// for the lookup. This is reference data for display only — a flag emoji is
// garnish (regional-indicator glyphs don't render on Windows Chrome/Firefox),
// the country name is the real signal. A few upstream rows misrouted prefixes
// the demo actually generates (VB–VG → Canada, ZL/ZM → New Zealand) or paired a
// country with the wrong flag (Lebanon, Palau, Macedonia); those are corrected
// here. This is not a full audit of the table — other rows may still be off.

export interface CallsignSeries {
  /** Inclusive prefix range, e.g. "CFA-CKZ" or "ZB2-ZB2". */
  series: string;
  country: string;
  /** Regional-indicator flag emoji, or "" for reserved/unallocated ranges. */
  flag: string;
}

export const CALLSIGN_SERIES: readonly CallsignSeries[] = [
  { series: 'AAA-ALZ', country: 'United States of America', flag: '🇺🇸' },
  { series: 'AMA-AOZ', country: 'Spain', flag: '🇪🇸' },
  { series: 'APA-ASZ', country: 'Pakistan', flag: '🇵🇰' },
  { series: 'ATA-AWZ', country: 'India', flag: '🇮🇳' },
  { series: 'AXA-AXZ', country: 'Australia', flag: '🇦🇺' },
  { series: 'AYA-AZZ', country: 'Argentina', flag: '🇦🇷' },
  { series: 'A2A-A2Z', country: 'Botswana', flag: '🇧🇼' },
  { series: 'A3A-A3Z', country: 'Tonga', flag: '🇹🇴' },
  { series: 'A4A-A4Z', country: 'Oman', flag: '🇴🇲' },
  { series: 'A5A-A5Z', country: 'Bhutan', flag: '🇧🇹' },
  { series: 'A6A-A6Z', country: 'United Arab Emirates', flag: '🇦🇪' },
  { series: 'A7A-A7Z', country: 'Qatar', flag: '🇶🇦' },
  { series: 'A8A-A8Z', country: 'Liberia', flag: '🇱🇷' },
  { series: 'A9A-A9Z', country: 'Bahrain', flag: '🇧🇭' },
  { series: 'BAA-BZZ', country: 'China', flag: '🇨🇳' },
  { series: 'CAA-CEZ', country: 'Chile', flag: '🇨🇱' },
  { series: 'CFA-CKZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'CLA-CMZ', country: 'Cuba', flag: '🇨🇺' },
  { series: 'CNA-CNZ', country: 'Morocco', flag: '🇲🇦' },
  { series: 'COA-COZ', country: 'Cuba', flag: '🇨🇺' },
  { series: 'CPA-CPZ', country: 'Bolivia', flag: '🇧🇴' },
  { series: 'CQA-CUZ', country: 'Portugal', flag: '🇵🇹' },
  { series: 'CVW-CZZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'DAA-DRZ', country: 'Germany', flag: '🇩🇪' },
  { series: 'DSA-DYZ', country: 'South Korea', flag: '🇰🇷' },
  { series: 'D4A-D4Z', country: 'Cape Verde', flag: '🇨🇻' },
  { series: 'D5A-D5Z', country: 'Liberia', flag: '🇱🇷' },
  { series: 'D6A-D6Z', country: 'Comoros', flag: '🇰🇲' },
  { series: 'D7A-D9Z', country: 'South Korea', flag: '🇰🇷' },
  { series: 'EAA-EHZ', country: 'Spain', flag: '🇪🇸' },
  { series: 'EIA-EJZ', country: 'Ireland', flag: '🇮🇪' },
  { series: 'EKA-EKZ', country: 'Armenia', flag: '🇦🇲' },
  { series: 'ELA-ELZ', country: 'Liberia', flag: '🇱🇷' },
  { series: 'EMA-EOZ', country: 'Ukraine', flag: '🇺🇦' },
  { series: 'EPA-EQZ', country: 'Iran', flag: '🇮🇷' },
  { series: 'ERA-ERZ', country: 'Moldova', flag: '🇲🇩' },
  { series: 'ESA-ESZ', country: 'Estonia', flag: '🇪🇪' },
  { series: 'ETA-ETZ', country: 'Ethiopia', flag: '🇪🇹' },
  { series: 'EUA-EWZ', country: 'Belarus', flag: '🇧🇾' },
  { series: 'EXA-EXZ', country: 'Kyrgyz Republic', flag: '🇰🇬' },
  { series: 'EYA-EYZ', country: 'Tajikistan', flag: '🇹🇯' },
  { series: 'EZA-EZZ', country: 'Turkmenistan', flag: '🇹🇲' },
  { series: 'E2A-E2Z', country: 'Thailand', flag: '🇹🇭' },
  { series: 'E3A-E3Z', country: 'Eritrea', flag: '🇪🇷' },
  { series: 'E4A-E4Z', country: 'Palestinian Authority', flag: '🇵🇸' },
  { series: 'E5A-E5Z', country: 'New Zealand (Cook Islands)', flag: '🇳🇿' },
  { series: 'E6A-E6Z', country: 'New Zealand (Niue)', flag: '🇳🇿' },
  { series: 'E7A-E7Z', country: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { series: 'FAA-FZZ', country: 'France', flag: '🇫🇷' },
  { series: 'GAA-GZZ', country: 'United Kingdom', flag: '🇬🇧' },
  { series: 'HAA-HAZ', country: 'Hungary', flag: '🇭🇺' },
  { series: 'HBA-HBZ', country: 'Switzerland', flag: '🇨🇭' },
  { series: 'HCA-HDZ', country: 'Ecuador', flag: '🇪🇨' },
  { series: 'HEA-HEZ', country: 'Switzerland', flag: '🇨🇭' },
  { series: 'HIA-HIZ', country: 'Hungary', flag: '🇭🇺' },
  { series: 'HJA-HKZ', country: 'Colombia', flag: '🇨🇴' },
  { series: 'HLA-HLZ', country: 'South Korea', flag: '🇰🇷' },
  { series: 'HMA-HMZ', country: 'Malaysia', flag: '🇲🇾' },
  { series: 'HNA-HNZ', country: 'Cambodia', flag: '🇰🇭' },
  { series: 'HOA-HOZ', country: 'Colombia', flag: '🇨🇴' },
  { series: 'HPA-HPZ', country: 'Panama', flag: '🇵🇦' },
  { series: 'HQA-HSZ', country: 'Honduras', flag: '🇭🇳' },
  { series: 'HTA-HTZ', country: 'Nicaragua', flag: '🇳🇮' },
  { series: 'HUA-HUZ', country: 'Uruguay', flag: '🇺🇾' },
  { series: 'HVA-HVZ', country: 'Vatican City', flag: '🇻🇦' },
  { series: 'HWA-HWZ', country: 'Panama', flag: '🇵🇦' },
  { series: 'HXA-HYZ', country: 'Ecuador', flag: '🇪🇨' },
  { series: 'H8A-H9Z', country: 'Panama', flag: '🇵🇦' },
  { series: 'IAA-IZZ', country: 'Italy', flag: '🇮🇹' },
  { series: 'JAA-JSZ', country: 'Japan', flag: '🇯🇵' },
  { series: 'JGA-JGZ', country: 'South Korea', flag: '🇰🇷' },
  { series: 'JHA-JIZ', country: 'South Korea', flag: '🇰🇷' },
  { series: 'JJA-JNZ', country: 'South Korea', flag: '🇰🇷' },
  { series: 'JOA-JSZ', country: 'Japan', flag: '🇯🇵' },
  { series: 'JTA-JUZ', country: 'North Korea', flag: '🇰🇵' },
  { series: 'JVA-JYZ', country: 'Japan', flag: '🇯🇵' },
  { series: 'JXA-JYZ', country: 'Japan', flag: '🇯🇵' },
  { series: 'KAA-KZZ', country: 'United States', flag: '🇺🇸' },
  { series: 'LAA-LAZ', country: 'Norway', flag: '🇳🇴' },
  { series: 'LBA-LBZ', country: 'Argentina', flag: '🇦🇷' },
  { series: 'LCA-LCZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'LDA-LDZ', country: 'Mexico', flag: '🇲🇽' },
  { series: 'LEA-LEZ', country: 'Argentina', flag: '🇦🇷' },
  { series: 'LFA-LFZ', country: 'Sweden', flag: '🇸🇪' },
  { series: 'LGA-LHZ', country: 'Sweden', flag: '🇸🇪' },
  { series: 'LIA-LIZ', country: 'Chile', flag: '🇨🇱' },
  { series: 'LJA-LKZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'LLA-LMZ', country: 'Argentina', flag: '🇦🇷' },
  { series: 'LNA-LNZ', country: 'Chile', flag: '🇨🇱' },
  { series: 'LOA-LSZ', country: 'Argentina', flag: '🇦🇷' },
  { series: 'LTA-LTZ', country: 'Mexico', flag: '🇲🇽' },
  { series: 'LUA-LYZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'LVA-LYZ', country: 'Argentina', flag: '🇦🇷' },
  { series: 'LXA-LYZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'LZA-LZZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'MAA-MZZ', country: 'United Kingdom', flag: '🇬🇧' },
  { series: 'NAA-NZZ', country: 'United States', flag: '🇺🇸' },
  { series: 'OAA-OAZ', country: 'Belgium', flag: '🇧🇪' },
  { series: 'OBA-OEZ', country: 'Finland', flag: '🇫🇮' },
  { series: 'OFA-OHZ', country: 'Finland', flag: '🇫🇮' },
  { series: 'OIA-OIZ', country: 'Ireland', flag: '🇮🇪' },
  { series: 'OJA-OKZ', country: 'Czech Republic', flag: '🇨🇿' },
  { series: 'OLA-OLZ', country: 'Czech Republic', flag: '🇨🇿' },
  { series: 'OMA-OMZ', country: 'Slovakia', flag: '🇸🇰' },
  { series: 'ONA-ONZ', country: 'Belgium', flag: '🇧🇪' },
  { series: 'OOA-OOZ', country: 'Belgium', flag: '🇧🇪' },
  { series: 'OPA-OPZ', country: 'Belgium', flag: '🇧🇪' },
  { series: 'OQA-OPZ', country: 'Luxembourg', flag: '🇱🇺' },
  { series: 'ORA-ORZ', country: 'Netherlands', flag: '🇳🇱' },
  { series: 'OSA-OSZ', country: 'Denmark', flag: '🇩🇰' },
  { series: 'OTA-OTZ', country: 'Belgium', flag: '🇧🇪' },
  { series: 'OUA-OUZ', country: 'Denmark', flag: '🇩🇰' },
  { series: 'OVA-OYZ', country: 'Finland', flag: '🇫🇮' },
  { series: 'OZA-OZZ', country: 'Denmark', flag: '🇩🇰' },
  { series: 'PAA-PBB', country: 'Norway', flag: '🇳🇴' },
  { series: 'PBA-PCZ', country: 'Netherlands', flag: '🇳🇱' },
  { series: 'PDA-PFZ', country: 'Netherlands', flag: '🇳🇱' },
  { series: 'PGA-PHZ', country: 'Indonesia', flag: '🇮🇩' },
  { series: 'PIA-PIZ', country: 'Indonesia', flag: '🇮🇩' },
  { series: 'PJA-PKZ', country: 'Indonesia', flag: '🇮🇩' },
  { series: 'PLA-PLZ', country: 'Poland', flag: '🇵🇱' },
  { series: 'PMA-PNZ', country: 'Poland', flag: '🇵🇱' },
  { series: 'POA-POZ', country: 'Poland', flag: '🇵🇱' },
  { series: 'PPA-PEZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'PFA-PHZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'PIA-PIZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'PJA-PJZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'PKA-PKZ', country: 'Indonesia', flag: '🇮🇩' },
  { series: 'PLA-PLZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'PMA-PNZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'POA-POZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'PPA-PZZ', country: 'Brazil', flag: '🇧🇷' },
  { series: 'P2A-P2Z', country: 'Papua New Guinea', flag: '🇵🇬' },
  { series: 'P3A-P3Z', country: 'Palestine', flag: '🇵🇸' },
  { series: 'P4A-P4Z', country: 'Netherlands Antilles', flag: '🇳🇱' },
  { series: 'P5A-P5Z', country: 'North Korea', flag: '🇰🇵' },
  { series: 'P6A-P6Z', country: 'North Korea', flag: '🇰🇵' },
  { series: 'P7A-P7Z', country: 'North Korea', flag: '🇰🇵' },
  { series: 'P8A-P8Z', country: 'North Korea', flag: '🇰🇵' },
  { series: 'P9A-P9Z', country: 'North Korea', flag: '🇰🇵' },
  {
    series: 'QAA-QNZ',
    country: 'Reserved for future ITU allocation',
    flag: '',
  },
  { series: 'QOA-QOZ', country: 'Reserved', flag: '' },
  { series: 'QPA-QZZ', country: 'Reserved', flag: '' },
  { series: 'RAA-RZZ', country: 'Russia', flag: '🇷🇺' },
  { series: 'SAA-SMZ', country: 'Sweden', flag: '🇸🇪' },
  { series: 'SNA-SZZ', country: 'South Korea', flag: '🇰🇷' },
  { series: 'S2A-S2Z', country: 'Singapore', flag: '🇸🇬' },
  { series: 'S3A-S3Z', country: 'Singapore', flag: '🇸🇬' },
  { series: 'S4A-S4Z', country: 'Singapore', flag: '🇸🇬' },
  { series: 'S5A-S5Z', country: 'Slovenia', flag: '🇸🇮' },
  { series: 'S6A-S6Z', country: 'Singapore', flag: '🇸🇬' },
  { series: 'S7A-S7Z', country: 'Singapore', flag: '🇸🇬' },
  { series: 'S8A-S8Z', country: 'Singapore', flag: '🇸🇬' },
  { series: 'S9A-S9Z', country: 'Singapore', flag: '🇸🇬' },
  { series: 'TAA-TOZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TPA-TPZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TQA-TSZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TTA-TTZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TUA-TUZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TVA-TVZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TWA-TWZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TXA-TXZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TYA-TYZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'TZA-TZZ', country: 'Turkey', flag: '🇹🇷' },
  { series: 'T2A-T2Z', country: 'Tuvalu', flag: '🇹🇻' },
  { series: 'T3A-T3Z', country: 'Kiribati', flag: '🇰🇮' },
  { series: 'T4A-T4Z', country: 'Cuba', flag: '🇨🇺' },
  { series: 'T5A-T5Z', country: 'Somalia', flag: '🇸🇴' },
  { series: 'T6A-T6Z', country: 'Afghanistan', flag: '🇦🇫' },
  { series: 'T7A-T7Z', country: 'Somalia', flag: '🇸🇴' },
  { series: 'T8A-T8Z', country: 'Palau', flag: '🇵🇼' },
  { series: 'T9A-T9Z', country: 'Bosnia', flag: '🇧🇦' },
  { series: 'UAA-UGZ', country: 'Russia', flag: '🇷🇺' },
  { series: 'UHA-UHZ', country: 'Russia', flag: '🇷🇺' },
  { series: 'UIA-UHZ', country: 'Russia', flag: '🇷🇺' },
  { series: 'UIA-UUZ', country: 'Russia', flag: '🇷🇺' },
  { series: 'UVA-UYZ', country: 'Russia', flag: '🇷🇺' },
  { series: 'UZA-UZZ', country: 'Russia', flag: '🇷🇺' },
  { series: 'U2A-U2Z', country: 'Ukraine', flag: '🇺🇦' },
  { series: 'U3A-U3Z', country: 'Ukraine', flag: '🇺🇦' },
  { series: 'U4A-U4Z', country: 'Ukraine', flag: '🇺🇦' },
  { series: 'VAA-VAZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'VBA-VCZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'VDA-VGZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'VHA-VHZ', country: 'Australia', flag: '🇦🇺' },
  { series: 'VIA-VIZ', country: 'Australia', flag: '🇦🇺' },
  { series: 'VJA-VKZ', country: 'Australia', flag: '🇦🇺' },
  { series: 'VLA-VLZ', country: 'Vietnam', flag: '🇻🇳' },
  { series: 'VMA-VNZ', country: 'Australia', flag: '🇦🇺' },
  { series: 'VOA-VOZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'VPA-VSZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'VTA-VTZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'VUA-VYZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'VZA-VZZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'V2A-V2Z', country: 'Antigua', flag: '🇦🇬' },
  { series: 'V3A-V3Z', country: 'Antigua', flag: '🇦🇬' },
  { series: 'V4A-V4Z', country: 'St. Lucia', flag: '🇱🇨' },
  { series: 'V5A-V5Z', country: 'Namibia', flag: '🇳🇦' },
  { series: 'V6A-V6Z', country: 'Philippines', flag: '🇵🇭' },
  { series: 'V7A-V7Z', country: 'Philippines', flag: '🇵🇭' },
  { series: 'V8A-V8Z', country: 'Philippines', flag: '🇵🇭' },
  { series: 'V9A-V9Z', country: 'Philippines', flag: '🇵🇭' },
  { series: 'WAA-WZZ', country: 'United States', flag: '🇺🇸' },
  { series: 'XAA-XIZ', country: 'China', flag: '🇨🇳' },
  { series: 'XJA-XOZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'XPA-XSZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'XTA-XSZ', country: 'Canada', flag: '🇨🇦' },
  { series: 'XTA-XTZ', country: 'Burkina Faso', flag: '🇧🇫' },
  { series: 'XUA-XUZ', country: 'Cambodia', flag: '🇰🇭' },
  { series: 'XVA-XVZ', country: 'Vietnam', flag: '🇻🇳' },
  { series: 'XWA-XWZ', country: 'Cambodia', flag: '🇰🇭' },
  { series: 'XXA-XYZ', country: 'China', flag: '🇨🇳' },
  { series: 'XZA-XZZ', country: 'Burkina Faso', flag: '🇧🇫' },
  { series: 'YAA-YEZ', country: 'Albania', flag: '🇦🇱' },
  { series: 'YFA-YHZ', country: 'Yemen', flag: '🇾🇪' },
  { series: 'YIA-YJZ', country: 'Venezuela', flag: '🇻🇪' },
  { series: 'YKA-YKZ', country: 'Lebanon', flag: '🇱🇧' },
  { series: 'YLA-YLZ', country: 'Latvia', flag: '🇱🇻' },
  { series: 'YMA-YMZ', country: 'Mexico', flag: '🇲🇽' },
  { series: 'YNA-YNZ', country: 'Nicaragua', flag: '🇳🇮' },
  { series: 'YOA-YOZ', country: 'Romania', flag: '🇷🇴' },
  { series: 'YPA-YPZ', country: 'Romania', flag: '🇷🇴' },
  { series: 'YQA-YQZ', country: 'Romania', flag: '🇷🇴' },
  { series: 'YRA-YSZ', country: 'Romania', flag: '🇷🇴' },
  { series: 'YTA-YTZ', country: 'Peru', flag: '🇵🇪' },
  { series: 'YUA-YYZ', country: 'Peru', flag: '🇵🇪' },
  { series: 'YVA-YVZ', country: 'Venezuela', flag: '🇻🇪' },
  { series: 'YWA-YWZ', country: 'Panama', flag: '🇵🇦' },
  { series: 'YYA-YYZ', country: 'Venezuela', flag: '🇻🇪' },
  { series: 'YZA-YZZ', country: 'Venezuela', flag: '🇻🇪' },
  { series: 'Y2A-Y2Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'Y3A-Y3Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'Y4A-Y4Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'Y5A-Y5Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'Y6A-Y6Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'Y7A-Y7Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'Y8A-Y8Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'Y9A-Y9Z', country: 'Germany', flag: '🇩🇪' },
  { series: 'ZA1A-ZA1Z', country: 'Albania', flag: '🇦🇱' },
  { series: 'ZB2-ZB2', country: 'Gibraltar', flag: '🇬🇧' },
  { series: 'ZC4-ZC4', country: 'British Forces Cyprus', flag: '🇬🇧' },
  { series: 'ZDA-ZHZ', country: 'South Africa', flag: '🇿🇦' },
  { series: 'ZIA-ZIZ', country: 'South Africa', flag: '🇿🇦' },
  { series: 'ZJA-ZKZ', country: 'New Zealand', flag: '🇳🇿' },
  { series: 'ZLA-ZMZ', country: 'New Zealand', flag: '🇳🇿' },
  { series: 'ZNA-ZOZ', country: 'Zambia', flag: '🇿🇲' },
  { series: 'ZPA-ZSZ', country: 'Zimbabwe', flag: '🇿🇼' },
  { series: 'ZTA-ZTZ', country: 'South Africa', flag: '🇿🇦' },
  { series: 'ZUA-ZYZ', country: 'South Africa', flag: '🇿🇦' },
  { series: 'ZZA-ZZZ', country: 'South Africa', flag: '🇿🇦' },
  { series: 'Z2A-Z2Z', country: 'Zimbabwe', flag: '🇿🇼' },
  { series: 'Z3A-Z3Z', country: 'Macedonia', flag: '🇲🇰' },
  { series: 'Z4A-Z4Z', country: 'Greece', flag: '🇬🇷' },
  { series: 'Z5A-Z5Z', country: 'Slovenia', flag: '🇸🇮' },
  { series: 'Z6A-Z6Z', country: 'Greece', flag: '🇬🇷' },
  { series: 'Z7A-Z7Z', country: 'Greece', flag: '🇬🇷' },
  { series: 'Z8A-Z8Z', country: 'Greece', flag: '🇬🇷' },
  { series: 'Z9A-Z9Z', country: 'Greece', flag: '🇬🇷' },
];
