// GENERATED by scripts/bake-hero-signal.ts — do not edit by hand.
// Regenerate:  bun run bake:hero -- --snr=-12 --noisy=sr8
//
// A REAL CW clip — "CQ CQ DE KC4T K" at 22 WPM, 700 Hz, seed 27 — generated by
// the morse-audio package and run through the model's DSP front-end (dsp.ts),
// resampled 22050→8000 Hz. Nothing here is synthesized.
//
//   HERO_NOISY  = short-window RMS (~1 ms) of the raw clip — preserves the real bar-to-bar noise variance instead of averaging it flat
//   HERO_KEYING = ideal on/off CW keying for the message — [on(1/0), units]
//                 segments at standard timing (dit 1, dah 3, gaps 1/3/7).
//                 145 units total.
//
// HONESTY: at -12 dB the decode is seed-dependent. Seed 27 is the first
// (of 1..500) whose ACTUAL CWNet output is letter-perfect. HERO_DECODED is
// that genuine output (raw letters "CQCQDEKC4TK", 88% confidence) with the
// message's word spacing restored for display — NOT the message constant. The
// bake throws unless the real decode matches, so a wrong decode can't ship.
// The noisy layer is intentionally unreadable by eye (honest at this SNR).
export const HERO_MESSAGE = 'CQ CQ DE KC4T K';
export const HERO_DECODED = 'CQ CQ DE KC4T K';
export const HERO_SNR_DB = -12;
export const HERO_CONFIDENCE = 0.883;
export const HERO_NOISY: number[] = [0.581, 0.453, 0.418, 0.656, 0.485, 0.663, 0.465, 0.716, 0.888, 1.000, 0.518, 0.575, 0.797, 0.899, 0.699, 0.564, 0.321, 0.454, 0.339, 0.675, 0.601, 0.379, 0.561, 0.862, 0.514, 0.437, 0.446, 0.447, 0.525, 0.328, 0.591, 0.531, 0.551, 0.368, 0.541, 0.404, 0.643, 0.344, 0.907, 0.570, 0.663, 0.564, 0.337, 0.832, 0.468, 0.505, 0.771, 0.803, 0.492, 0.672, 0.980, 0.555, 0.656, 0.702, 0.495, 0.677, 0.608, 0.661, 0.626, 0.640, 0.450, 0.630, 0.652, 0.672, 0.523, 0.498, 0.564, 0.829, 0.598, 0.900, 0.554, 0.683, 0.544, 0.780, 0.827, 0.517, 0.480, 0.783, 0.827, 0.709];
export const HERO_KEYING: [number, number][] = [[1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 1], [1, 1], [0, 3], [1, 3], [0, 1], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 7], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 1], [1, 1], [0, 3], [1, 3], [0, 1], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 7], [1, 3], [0, 1], [1, 1], [0, 1], [1, 1], [0, 3], [1, 1], [0, 7], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 3], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 1], [1, 1], [0, 3], [1, 1], [0, 1], [1, 1], [0, 1], [1, 1], [0, 1], [1, 1], [0, 1], [1, 3], [0, 3], [1, 3], [0, 7], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3]];
