// GENERATED by scripts/bake-hero-signal.ts — do not edit by hand.
// Regenerate:  bun run bake:hero -- --snr=-12 --noisy=sr8
//
// A REAL CW clip — "CQ CQ DE KC4T" at 22 WPM, 700 Hz, seed 4 — generated by
// the morse-audio package and run through the model's DSP front-end (dsp.ts),
// resampled 22050→8000 Hz. Nothing here is synthesized.
//
//   HERO_NOISY  = short-window RMS (~1 ms) of the raw clip — preserves the real bar-to-bar noise variance instead of averaging it flat
//   HERO_KEYING = ideal on/off CW keying for the message — [on(1/0), units]
//                 segments at standard timing (dit 1, dah 3, gaps 1/3/7).
//                 129 units total.
//
// HONESTY: at -12 dB the decode is seed-dependent. Seed 4 is the first
// (of 1..500) whose ACTUAL CWNet output is letter-perfect. HERO_DECODED is
// that genuine output (raw letters "CQCQDEKC4T", 93% confidence) with the
// message's word spacing restored for display — NOT the message constant. The
// bake throws unless the real decode matches, so a wrong decode can't ship.
// The noisy layer is intentionally unreadable by eye (honest at this SNR).
export const HERO_MESSAGE = 'CQ CQ DE KC4T';
export const HERO_DECODED = 'CQ CQ DE KC4T';
export const HERO_SNR_DB = -12;
export const HERO_CONFIDENCE = 0.929;
export const HERO_NOISY: number[] = [0.631, 0.862, 0.355, 0.622, 0.576, 0.466, 0.645, 0.760, 0.391, 0.601, 0.900, 0.802, 0.663, 0.494, 0.742, 0.576, 0.835, 0.661, 0.397, 0.494, 0.251, 0.542, 0.746, 0.494, 0.582, 0.712, 0.425, 0.382, 1.000, 0.628, 0.707, 0.386, 0.608, 0.413, 0.545, 0.785, 0.479, 0.576, 0.726, 0.756, 0.389, 0.361, 0.802, 0.963, 0.224, 0.638, 0.764, 0.598, 0.308, 0.532, 0.374, 0.412, 0.626, 0.316, 0.643, 0.660, 0.672, 0.853, 0.702, 0.595, 0.738, 0.539, 0.571, 0.491, 0.644, 0.863, 0.642, 0.617, 0.740, 0.421, 0.709, 0.878, 0.693, 0.473, 0.367, 0.500, 0.545, 0.994, 0.534, 0.484];
export const HERO_KEYING: [number, number][] = [[1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 1], [1, 1], [0, 3], [1, 3], [0, 1], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 7], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 1], [1, 1], [0, 3], [1, 3], [0, 1], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 7], [1, 3], [0, 1], [1, 1], [0, 1], [1, 1], [0, 3], [1, 1], [0, 7], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 3], [1, 3], [0, 1], [1, 1], [0, 1], [1, 3], [0, 1], [1, 1], [0, 3], [1, 1], [0, 1], [1, 1], [0, 1], [1, 1], [0, 1], [1, 1], [0, 1], [1, 3], [0, 3], [1, 3]];
